manifest:
  remotes:
    - name: nxtkb
      url-base: https://github.com/nxtkb
  projects:
    - name: zmk-behavior-send-string
      remote: nxtkb
      revision: 96fad37f0dc9bfcc32b8fd6c51233e5285b36250
